'use client';
import {useState} from 'react';
import data from '@/data/aggregates/infrastructure-series.json';
import './analysis-workspace.css';
import './infrastructure-series.css';
import {classifyDay,NON_COLLECTION_LABEL,weekdayName} from '@/lib/collection-calendar';
// The excluded days are not anonymous: naming them turns a threshold into an explanation.
const dayNote=(date:string)=>{const c=classifyDay(date);return c&&c!=='working'?`${date} (${NON_COLLECTION_LABEL[c]})`:`${date} (${weekdayName(date)??'unclassified'})`;};
const n=(v:number)=>v.toLocaleString('en-IN'),pct=(v:number|null)=>v===null?'Not reported':`${(v*100).toFixed(2)}%`;
const labels:Record<string,string>={'with-centre':'Registered with centre','without-centre':'Registered without centre','not-stated':'Presence not stated'};
export function InfrastructureSeries(){
 const [period,setPeriod]=useState(data.series.at(-1)!.period),[basis,setBasis]=useState<'comparable'|'full'|'sensitivity'>('comparable');
 const selected=data.series.find(s=>s.period===period)!,groups=selected[basis],a=groups.find(g=>g.id==='with-centre')!,b=groups.find(g=>g.id==='without-centre')!,difference=a.rate===null||b.rate===null?null:(a.rate-b.rate)*100;
 return <section className="evidence-workspace infrastructure-series" aria-label="Infrastructure and activity across retained months"><header className="ew-heading"><div><span className="ew-kicker">Infrastructure & activity · May → August</span><h2>Does the pattern hold<br/><em>across the months?</em></h2><p>Compare reported collection by processing-centre registration. The facility register has no effective date.</p></div><span className="rc-status">{data.series.length} retained months</span></header>
 <div className="ew-controls"><label>Evidence basis<select aria-label="Infrastructure evidence basis" value={basis} onChange={e=>setBasis(e.target.value as typeof basis)}><option value="comparable">Same first-week cohort · compare months</option><option value="full">All retained days · monthly context</option><option value="sensitivity">Exclude low-reporting days · sensitivity only</option></select></label><label>Inspect month<select aria-label="Infrastructure month" value={period} onChange={e=>setPeriod(e.target.value)}>{data.series.map(s=><option key={s.period}>{s.period}</option>)}</select></label></div>
 <p className="ew-caption">{basis==='comparable'?`${n(data.commonObservations)} registered GP/day-of-month observations with valid collection reports in every month; days 1–${data.windowDays}. Each window holds exactly one Sunday, so both register groups carry the same scheduled non-collection day and the comparison between them is unaffected.`:basis==='full'?'Every retained day is included. Month lengths and reporting populations differ; these are context rates.':`Sensitivity excludes dates with less than 20% Yes among valid source reports. Almost every date this removes is a scheduled non-collection day. Every retained Sunday and each month's second Saturday is removed, so this reads closer to a working-day rate than to an outage adjustment. Exclusions are named below.`}</p>
 <div className="ew-reading"><div className="ew-primary"><span>{period} · with centre minus without</span><strong>{difference===null?'—':`${difference>0?'+':''}${difference.toFixed(2)}`} <small>percentage points</small></strong><p>Difference in reported collection rates</p><small>{difference===null?'A group lacks valid observations.':`The registered-with-centre group reports ${Math.abs(difference).toFixed(2)} percentage points ${difference>=0?'higher':'lower'}.`} This does not establish an infrastructure effect.</small></div><div className="ew-chart-panel"><h3>Collection reporting by register status</h3><svg viewBox="0 0 600 250" role="img" aria-label="Monthly collection rates by facility presence"><line x1="55" y1="205" x2="550" y2="205"/>
   {/* The separation between the two groups is the whole finding, and the chart drew
       everything except it. Shading the band makes how small it is the first thing
       visible, rather than something the reader has to measure off two lines. */}
   {basis==='comparable'&&(()=>{
     const pts=(id:string)=>data.series.flatMap((s,i)=>{const r=s[basis].find(g=>g.id===id)?.rate;return r==null?[]:[[80+i*145,205-r*165] as const];});
     const top=pts('with-centre'), bottom=pts('without-centre');
     if(top.length!==data.series.length||bottom.length!==data.series.length) return null;
     return <polygon className="infra-band" points={[...top,...[...bottom].reverse()].map(([x,y])=>`${x},${y}`).join(' ')}/>;
   })()}{[0,50,100].map(v=><g key={v}><line x1="55" x2="550" y1={205-v*1.65} y2={205-v*1.65}/><text x="45" y={209-v*1.65} textAnchor="end">{v}%</text></g>)}{['with-centre','without-centre'].map((id,j)=><g key={id} className={`infra-line infra-line-${j}`}>{basis==='comparable'&&<polyline fill="none" points={data.series.flatMap((s,i)=>{const r=s[basis].find(g=>g.id===id)?.rate;return r==null?[]:[`${80+i*145},${205-r*165}`];}).join(' ')}/>} {data.series.map((s,i)=>{const r=s[basis].find(g=>g.id===id)?.rate;return r==null?null:<circle key={s.period} cx={80+i*145} cy={205-r*165} r="5"><title>{`${s.period}: ${labels[id]} ${pct(r)}`}</title></circle>;})}</g>)}{data.series.map((s,i)=><text key={s.period} x={80+i*145} y="235" textAnchor="middle">{s.period}</text>)}</svg><p className="infra-legend"><span>● With centre</span><span>● Without centre</span></p><p className="ew-caption">Full 0–100% scale. Exact values and denominators are below.</p></div></div>
 <div className="ew-table-scroll"><table><thead><tr><th>Month</th><th>With centre</th><th>Without centre</th><th>Difference<small className="th-unit">percentage points</small></th><th>Valid GP-days</th></tr></thead><tbody>{data.series.map(s=>{const x=s[basis].find(g=>g.id==='with-centre')!,y=s[basis].find(g=>g.id==='without-centre')!;return <tr key={s.period}><th><button onClick={()=>setPeriod(s.period)} aria-pressed={period===s.period}>{s.period}</button></th><td>{pct(x.rate)}</td><td>{pct(y.rate)}</td><td>{x.rate===null||y.rate===null?'—':`${(x.rate-y.rate)*100>0?'+':''}${((x.rate-y.rate)*100).toFixed(2)}`}</td><td>{n(s[basis].reduce((sum,g)=>sum+g.valid,0))}</td></tr>;})}</tbody></table></div>
 <div className="ew-table-scroll"><h3>{period} · the observations behind the comparison</h3><table><thead><tr><th>Register status</th><th>GPs</th><th>Yes / valid GP-days</th><th>Collection rate</th><th>Missing responses</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><th>{labels[g.id]}</th><td>{n(g.panchayats)}</td><td>{n(g.yes)} / {n(g.valid)}</td><td>{pct(g.rate)}</td><td>{n(g.missing)}</td></tr>)}</tbody></table></div>
 <p className="ew-notice">The register describes recorded facility status at an unknown date. Differences may reflect reporting, geography or other factors. Similar rates do not establish equivalence; low rates do not establish an infrastructure gap.</p>
 <details><summary>{period} · centre condition and district breakdowns</summary><p>All retained days in this month; these context groups are not the matched first-week cohort.</p><div className="ew-table-scroll"><table><thead><tr><th>Registered centre condition</th><th>GPs</th><th>Collection rate</th><th>Valid GP-days</th></tr></thead><tbody>{selected.byCondition.map(g=><tr key={g.condition}><th>{g.condition}</th><td>{n(g.panchayats)}</td><td>{pct(g.rate)}</td><td>{n(g.valid)}</td></tr>)}</tbody></table><table><thead><tr><th>District</th><th>With centre</th><th>Without centre</th></tr></thead><tbody>{selected.byDistrict.map(d=><tr key={d.district}><th>{d.district}</th><td>{pct(d.groups.find(g=>g.id==='with-centre')!.rate)}</td><td>{pct(d.groups.find(g=>g.id==='without-centre')!.rate)}</td></tr>)}</tbody></table></div></details>
 <details><summary>Coverage, exclusions and low-reporting-day sensitivity</summary>{data.series.map(s=><p key={s.period}><b>{s.period}</b>: {s.days.length} retained days · {n(s.quality.rawRows)} raw / {n(s.quality.uniqueRows)} distinct GP-days · {n(s.quality.conflictingRows+s.quality.missingKeyRows)} conflicting or unidentified rows excluded · {n(s.matchedPanchayats)} registered GPs matched · {n(s.unmatchedObservations)} observations outside the register. Low-reporting dates: {s.lowDays.map(dayNote).join(', ')||'none'}.</p>)}<p>{data.register.disputed} disputed register identities excluded. {data.boundary}</p></details>
 </section>;
}
