'use client';
import {useState} from 'react';
import {getRevisionAnalysis,getRevisionInventory,revisionMeasures} from '@/lib/source-revisions';
import './analysis-workspace.css';
import './evidence-expansion.css';
const label=(value:string|null)=>value?.replace(/^"|"$/g,'')??'Not supplied';
const n=(v:number|null)=>v===null?'Not reported':v.toLocaleString('en-IN',{maximumFractionDigits:2});
export function SourceRevisions(){
  const [measure,setMeasure]=useState('e-autos');const [period,setPeriod]=useState<string>();const [district,setDistrict]=useState('');
  const data=getRevisionAnalysis(measure,period);const inventory=getRevisionInventory();const changed=inventory.filter(row=>row.changed);
  const rows=data.rows.filter(row=>!district||row.district===district).sort((a,b)=>(a.entity??'').localeCompare(b.entity??''));
  return <section className="evidence-workspace revision-workspace" aria-labelledby="revisions-title">
    <header className="ew-heading"><div><span className="ew-kicker">Current responses · explicit source revision</span><h1 id="revisions-title">What changed in the source.</h1><p>{inventory.length} current responses checked against the active historical records: {inventory.length-changed.length} unchanged, {changed.length} revised. Read the new measures in their own scope.</p></div></header>
    <div className="ew-controls"><label>Revised measure<select value={measure} onChange={e=>{setMeasure(e.target.value);setPeriod(undefined);setDistrict('');}}>{revisionMeasures.map(spec=><option key={spec.id} value={spec.id}>{spec.label} · {spec.grain}</option>)}</select></label>{data.periods.length>0&&<label>Source period<select value={data.selectedPeriod??''} onChange={e=>{setPeriod(e.target.value);setDistrict('');}}>{data.periods.map(p=><option key={p}>{p}</option>)}</select></label>}</div>
    <p className="ew-notice">{data.spec.change}</p>
    <div className="revision-position" role="group" aria-label="Revised source position"><div><span>{data.spec.label} · {data.selectedPeriod??'Reporting period not supplied'}</span><strong>{n(data.achievement)}</strong><p>{data.spec.unit} achievement reported</p></div><div><span>Target in the same source</span><strong>{n(data.target)}</strong><p>{data.spec.unit}</p></div><div><span>Achievement / target</span><strong>{data.ratio===null?'No rate':`${(data.ratio*100).toFixed(1)}%`}</strong><p>{data.paired} candidates with both measures</p></div></div>
    <div className="movement-ledger"><span><b>{data.rawRows}</b> rows in this response</span><span><b>{data.rows.length}</b> usable source-name candidates · selected period</span><span><b>{data.quality.duplicateRows}</b> repeated measure pairs collapsed · selected period</span><span><b>{data.quality.conflictingRows+data.quality.missingKeyRows}</b> rows held out · selected period</span></div>
    <p className="ew-caption">{data.missingMeasure} usable candidates lack a target or achievement and are excluded from the rate. {data.identicalRoutes.length} of {data.spec.routes.length} listed routes return identical row content; only the named canonical response supplies this measure.</p>
    <section className="ew-table-section"><header><div><h3>Inspect the places behind the measure</h3><p className="ew-caption">Source-name candidates · {data.spec.grain} grain · {data.spec.unit}. District filtering affects the table; the source-wide position above stays visible.</p></div><label>District<select value={district} onChange={e=>setDistrict(e.target.value)}>{['',...new Set(data.rows.map(row=>row.district??''))].map(d=><option key={d} value={d}>{d?label(d):'All returned districts'}</option>)}</select></label></header><div className="ew-table-scroll"><table><thead><tr><th>{data.spec.grain==='ULB'?'ULB source name':'District'}</th>{data.spec.grain==='ULB'&&<th>District</th>}<th>Target</th><th>Achievement</th></tr></thead><tbody>{rows.map(row=><tr key={row.key}><th scope="row">{label(row.entity)}</th>{data.spec.grain==='ULB'&&<td>{label(row.district)}</td>}<td>{n(row.target)}</td><td>{n(row.achievement)}</td></tr>)}</tbody></table></div></section>
    <details className="vi-disclosure"><summary>All {inventory.length} retained revised responses · coverage inventory</summary><p>Retention means the response is available for inspection. Only validated, explicitly defined measures enter the analytical views; changed schemas do not silently replace historical measurements.</p><div className="ew-table-scroll"><table><thead><tr><th>Source route</th><th>Historical rows</th><th>Current rows</th><th>Content comparison</th></tr></thead><tbody>{inventory.map(row=><tr key={row.key}><th scope="row">{row.key}</th><td>{row.activeRows}</td><td>{row.currentRows}</td><td>{row.changed?'Revised response':'Same retained content'}</td></tr>)}</tbody></table></div></details>
    <div className="ew-evidence"><details><summary>Revision scope, fields and retention</summary><div><p>Canonical route: <code>{data.spec.routes[0]}</code>. Source response generated {data.retainedAt}. Measurement fields: <code>{data.spec.target}</code> and <code>{data.spec.achievement}</code>.</p><p>The current response is used in this revision view. Historical urban reviews retain their labelled source vintage; the changed service-model route cannot replace ULB procurement records. No cross-vintage change is inferred from unpaired source totals.</p><p>Current account catalogue: 42 routes. Twenty-six responses are retained here; this is not a certificate that the entire lake is ingested. Completed May–August rural pulls are loaded separately in the monthly trend and infrastructure analyses. Routes without a completed fresh export retain their explicitly labelled historical evidence.</p></div></details></div>
  </section>;
}
