'use client';
import {useEffect,useMemo,useState} from 'react';
import {getRankingDefinition,getSubjectProfile,rankSubject,rankPrecision,rankingDiagnosticLink,rankingSubjects,type RankingSubject} from '@/lib/subject-rankings';
import './subject-rankings.css';
import {RadarNames} from './radar-names';
import {getOverallReadiness} from '@/lib/overall-readiness';
import './overall-readiness.css';
import {observedMedian} from '@/lib/visual-evidence';

const n=(v:number)=>v.toLocaleString('en-IN',{maximumFractionDigits:2});
type FieldState='higher-wide'|'higher-compact'|'lower-wide'|'lower-compact';
const fieldStates:[FieldState,string,string,string][]=[
  ['higher-wide','Higher rate · larger workload','Doing well at scale','Higher reported completion with a larger denominator.'],
  ['higher-compact','Higher rate · smaller workload','Doing well','Higher reported completion with a smaller denominator.'],
  ['lower-wide','Lower rate · larger workload','Investigate delivery at scale','Lower reported completion with more work reported.'],
  ['lower-compact','Lower rate · smaller workload','Review delivery','Lower reported completion with a smaller denominator.'],
];
const fieldState=(rate:number,workload:number,rateMedian:number,workloadMedian:number):FieldState=>(rateMedian===0?rate>0:rate>=rateMedian)?(workload>=workloadMedian?'higher-wide':'higher-compact'):(workload>=workloadMedian?'lower-wide':'lower-compact');
function SubjectFieldRadar({definition,rows,allRows,selected,onSelect,query}:{definition:ReturnType<typeof getRankingDefinition>;rows:ReturnType<typeof rankSubject>['rows'];allRows:ReturnType<typeof rankSubject>['rows'];selected:string;onSelect:(key:string)=>void;query:string}){
  const rateMedian=observedMedian(allRows.map(r=>r.rate))??50,workloadMedian=observedMedian(allRows.map(r=>r.bottom!))??1,maxWorkload=Math.max(1,...allRows.map(r=>r.bottom!));
  const magnitude=10**Math.floor(Math.log10(maxWorkload)),ceiling=Math.ceil(maxWorkload/magnitude)*magnitude;
  const left=70,top=60,width=720,height=430,x=(value:number)=>left+value/ceiling*width,y=(rate:number)=>top+height-rate/100*height;
  const groups=[...rows.reduce((map,row)=>{const key=`${row.bottom}|${row.rate}`;const group=map.get(key)??{bottom:row.bottom!,rate:row.rate,rows:[] as typeof rows};group.rows.push(row);map.set(key,group);return map;},new Map<string,{bottom:number;rate:number;rows:typeof rows}>()).values()];
  const counts=Object.fromEntries(fieldStates.map(([id])=>[id,rows.filter(r=>fieldState(r.rate,r.bottom!,rateMedian,workloadMedian)===id).length]));
  const examples=Object.fromEntries(fieldStates.map(([id])=>{const members=rows.filter(r=>fieldState(r.rate,r.bottom!,rateMedian,workloadMedian)===id),highest=[...members].sort((a,b)=>b.rate-a.rate||b.bottom!-a.bottom!)[0],lowest=[...members].sort((a,b)=>a.rate-b.rate||a.bottom!-b.bottom!)[0];return [id,{highest,lowest}]})) as Record<FieldState,{highest:typeof rows[number]|undefined;lowest:typeof rows[number]|undefined}>;
  const xMedian=x(workloadMedian),yMedian=y(rateMedian);
  return <section className="rk-field" aria-label={`${definition.label} ranking graph`}>
    <header><div><span className="rk-kicker">ULB performance field · subject view</span><h3>{definition.label} · ULB comparison</h3></div><span>{query.trim()?`${rows.length} matches`:`${rows.length} eligible ULBs`} · {definition.period}</span></header>
    <div className="rk-field-stage"><div className="rk-field-plot"><div className="rk-field-scroll"><svg viewBox="0 0 840 555" role="group" aria-label={`${definition.label} ULB workload versus reported completion rate`}>
      <rect x={left} y={top} width={xMedian-left} height={yMedian-top} className="rk-field-zone rk-field-higher-compact"/><rect x={xMedian} y={top} width={left+width-xMedian} height={yMedian-top} className="rk-field-zone rk-field-higher-wide"/><rect x={left} y={yMedian} width={xMedian-left} height={top+height-yMedian} className="rk-field-zone rk-field-lower-compact"/><rect x={xMedian} y={yMedian} width={left+width-xMedian} height={top+height-yMedian} className="rk-field-zone rk-field-lower-wide"/>
      {[0,25,50,75,100].map(t=><g key={t}><line x1={left} x2={left+width} y1={y(t)} y2={y(t)} className="rk-field-grid"/><line x1={x(t===0?0:ceiling*t/100)} x2={x(t===0?0:ceiling*t/100)} y1={top} y2={top+height} className="rk-field-grid"/><text x={left-11} y={y(t)+4} textAnchor="end" className="rk-field-tick">{t}%</text><text x={x(ceiling*t/100)} y={top+height+22} textAnchor="middle" className="rk-field-tick">{n(ceiling*t/100)}</text></g>)}
      <line x1={xMedian} x2={xMedian} y1={top} y2={top+height} className="rk-field-reference"/><line x1={left} x2={left+width} y1={yMedian} y2={yMedian} className="rk-field-reference"/>
      <text x={left+12} y={top+22} className="rk-field-zone-label">{fieldStates[1][2]}</text><text x={left+width-12} y={top+22} textAnchor="end" className="rk-field-zone-label">{fieldStates[0][2]}</text><text x={left+12} y={top+height-14} className="rk-field-zone-label">{fieldStates[3][2]}</text><text x={left+width-12} y={top+height-14} textAnchor="end" className="rk-field-zone-label">{fieldStates[2][2]}</text>
      <text x={left+width/2} y="548" textAnchor="middle" className="rk-field-axis">Reported workload · {definition.bottomLabel}</text><text transform="translate(17 275) rotate(-90)" textAnchor="middle" className="rk-field-axis">Reported completion rate · {definition.topLabel} / {definition.bottomLabel}</text>
      {groups.map(group=>{const active=group.rows.some(r=>r.key===selected),state=fieldState(group.rate,group.bottom,rateMedian,workloadMedian),name=group.rows.map(r=>r.name).join(', ');return <g key={`${group.bottom}|${group.rate}`} role="button" tabIndex={0} aria-label={`${name}: ${n(group.rate)}% reported completion, ${n(group.bottom)} ${definition.bottomLabel}; ${fieldStates.find(s=>s[0]===state)![1]}`} aria-pressed={active} className={`rk-field-dot rk-field-${state} ${active?'is-selected':''}`} onClick={()=>onSelect(group.rows[0].key)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(group.rows[0].key);}}}><circle cx={x(group.bottom)} cy={y(group.rate)} r="14" fill="transparent"/><circle cx={x(group.bottom)} cy={y(group.rate)} r={active?9:group.rows.length>1?7:5} className="rk-field-mark"/>{group.rows.length>1&&<text x={x(group.bottom)} y={y(group.rate)+3} textAnchor="middle" className="rk-field-count">{group.rows.length}</text>}{active&&<text x={group.bottom>ceiling*.72?x(group.bottom)-12:x(group.bottom)+12} y={y(group.rate)+(group.rate>90?22:-14)} textAnchor={group.bottom>ceiling*.72?'end':'start'} className="rk-field-name">{group.rows.find(r=>r.key===selected)?.name}</text>}<title>{`${name} · ${n(group.rate)}% · ${n(group.bottom)} ${definition.bottomLabel}`}</title></g>;})}
      <RadarNames points={[...new Map(fieldStates.flatMap(([id])=>[examples[id].highest,examples[id].lowest]).filter(r=>r&&r.key!==selected).map(r=>[r!.key,{key:r!.key,name:r!.name,x:x(r!.bottom!),y:y(r!.rate)}])).values()]}/>
    </svg></div><p className="rk-caption">Each dot is an eligible source ULB. Dashed guides are the observed cohort medians: {n(rateMedian)}% completion and {n(workloadMedian)} reported {definition.bottomLabel.toLowerCase()}. {rateMedian===0?'Because the rate median is zero, only positive rates sit above the horizontal guide; zero reports remain below it. ':''}They organize comparison only; they are not policy targets or an overall score.</p></div><aside className="rk-field-categories" aria-label="Subject comparison fields"><span className="rk-kicker">Reading the field</span>{fieldStates.map(([id,,labelText,description])=>{const example=examples[id];return <button key={id} className={`rk-field-card rk-field-${id}`} aria-pressed={false} onClick={()=>{const first=rows.find(r=>fieldState(r.rate,r.bottom!,rateMedian,workloadMedian)===id);if(first)onSelect(first.key);}}><span><b>{labelText}</b><strong>{counts[id]}</strong></span><small>{description}</small>{example.highest?<div className="rk-field-examples"><span>{id.startsWith('higher')?'Potential learning peer':'Highest reported rate'} <b>{example.highest.name}</b><em>{n(example.highest.rate)}%</em></span>{example.lowest&&example.lowest.key!==example.highest.key&&<span>Lowest reported rate <b>{example.lowest.name}</b><em>{n(example.lowest.rate)}%</em></span>}</div>:<div className="rk-field-examples is-empty">None in this cohort</div>}</button>;})}<p>Higher and lower describe the reported rate relative to this cohort. Workload describes the source denominator, so a larger field is not automatically a worse outcome.</p></aside></div>
  </section>;
}
export function SubjectRankings(){
  const definitions=useMemo(()=>rankingSubjects.map(s=>getRankingDefinition(s.id)),[]);
  const overallReadiness=useMemo(()=>getOverallReadiness(),[]);
  const [subject,setSubject]=useState<RankingSubject>('reach'),[district,setDistrict]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState('urban:1136');
  useEffect(()=>{const p=new URLSearchParams(window.location.search),id=p.get('subject');if(rankingSubjects.some(s=>s.id===id)){
    /* eslint-disable react-hooks/set-state-in-effect */
    setSubject(id as RankingSubject);setSelected(p.get('entity')??'');
    /* eslint-enable react-hooks/set-state-in-effect */
  }},[]);
  const definition=definitions.find(d=>d.id===subject)!;
  const data=rankSubject(definition.inputs,district),all=rankSubject(definition.inputs);
  const visible=data.rows.filter(r=>`${r.name} ${r.district}`.toLowerCase().includes(query.trim().toLowerCase()));
  const excluded=data.excluded.filter(r=>`${r.name} ${r.district}`.toLowerCase().includes(query.trim().toLowerCase()));
  const chosen=definition.inputs.find(r=>r.key===selected&&(!district||r.district===district));
  const position=data.rows.find(r=>r.key===selected),held=data.excluded.find(r=>r.key===selected);
  const graphRows=query.trim()?visible:data.rows;
  if(position&&!graphRows.some(r=>r.key===position.key)) graphRows.push(position);
  const profile=chosen?getSubjectProfile(chosen,subject,definitions):[];
  const link=chosen?rankingDiagnosticLink(definition,chosen):null;
  const districts=[...new Set(definition.inputs.map(r=>r.district))].sort();
  const changeSubject=(id:RankingSubject,key='')=>{setSubject(id);setDistrict('');setQuery('');setSelected(key);if(key)document.getElementById('subject-rankings')?.scrollIntoView({block:'start'});};
  const inspect=(key:string,reveal=false)=>{setSelected(key);if(reveal||window.innerWidth<=760)document.getElementById('subject-ranking-selected')?.scrollIntoView({block:'start'});};
  const first=profile.find(p=>p.definition.id==='reach'),second=profile.find(p=>p.definition.id==='segregation');
  const reading=first?.ranked&&second?.ranked?`Collection reaches ${n(first.ranked.rate)}% of reported households. Of collected households, ${n(second.ranked.rate)}% report segregation. ${n(first.ranked.bottom!-first.ranked.top!)} households are not recorded as collected; ${n(second.ranked.bottom!-second.ranked.top!)} collected households are not recorded as segregating.`:
    position?`${n(position.top!)} ${definition.topLabel.toLowerCase()} against ${n(position.bottom!)} ${definition.bottomLabel.toLowerCase()}. ${n(position.bottom!-position.top!)} remain against this reported denominator.`:'An eligible rate is unavailable. Missing or disputed evidence does not mean poor performance.';
  return <section id="subject-rankings" className="subject-rankings" aria-label="Subject rankings and ULB profiles">
    <header className="rk-intro"><div><span className="rk-kicker">Reported performance · one subject at a time</span><h2>ULB subject rankings</h2><p>Rank eligible ULBs on a defined rate, then inspect their evidence profile. Each subject keeps its own reporting period.</p></div><span className="rk-badge">5 measures · no overall score</span></header>
    <div className="rk-controls"><label>Subject<select aria-label="Ranking subject" value={subject} onChange={e=>changeSubject(e.target.value as RankingSubject)}>{rankingSubjects.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label>Comparison population<select aria-label="Ranking population" value={district} onChange={e=>{setDistrict(e.target.value);setSelected('');setQuery('');}}><option value="">All returned districts</option>{districts.map(d=><option key={d}>{d}</option>)}</select></label><label>Find a ULB<input type="search" aria-label="Search ranked ULBs" placeholder="Search name or district" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
    <div className="rk-basis"><div><span>Ranking basis · higher rate first</span><strong>{definition.topLabel} ÷ {definition.bottomLabel} × 100</strong><small>{definition.period} · {district||'All returned districts'}</small></div><div><strong>{data.rows.length}<small>eligible</small></strong><span>of {data.population} returned candidates</span></div><div><strong>{data.excluded.length}<small>not ranked</small></strong><span>Reasons remain visible below</span></div></div>
    <p className="rk-caption">Ranks compare this subject only. Equal rates share a rank (1, 1, 3); measured to six decimal places, displayed to two. District selection recalculates ranks; search only finds rows. There is no draft target in this ordering.</p>
    <details className="rk-overall-audit" id="overall-readiness"><summary><b>Overall delivery signal audit</b><span>Gated · {overallReadiness.validThreeSubjectCandidates} of {overallReadiness.exactCandidateOverlap} exact-name candidates have three valid July measures</span></summary><div className="rk-audit-grid"><div><strong>{overallReadiness.exactCandidateOverlap}</strong><span>exact name + district overlap</span></div><div><strong>{overallReadiness.validThreeSubjectCandidates}</strong><span>valid in all 3 delivery subjects</span></div><div><strong>{overallReadiness.zeroToiletAndVehicle}</strong><span>with zero toilet and vehicle rates</span></div><div><strong>{n(overallReadiness.validCoveragePercent)}%</strong><span>of exact overlap retained</span></div></div><p>We tested a July composite across household toilets, vehicle supply and legacy-waste clearance. Its valid cohort is only {overallReadiness.validThreeSubjectCandidates}; {overallReadiness.zeroToiletAndVehicle} of those rows have zero in the first two measures, so a blended score would mostly reflect two zero reports rather than comparable ULB delivery. No shared canonical ULB code is carried by all three source families; the overlap is exact source name + district only. An overall rank stays gated until the source families carry a reviewed common identity, the zero patterns are explained, and subject weights are approved.</p></details>
    <SubjectFieldRadar definition={definition} rows={graphRows} allRows={data.rows} selected={selected} onSelect={inspect} query={query}/>
    <div className="rk-workspace"><div className="rk-list"><header><h3>{definition.label}</h3><span>{visible.length} of {data.rows.length} eligible shown</span></header><div className="rk-table-wrap"><table><thead><tr><th>Rank</th><th>ULB / source candidate</th><th>Rate</th><th>Reported quantities</th></tr></thead><tbody>{visible.map(r=><tr key={r.key} className={r.key===selected?'is-selected':''}><td><b>{r.rank}</b>{r.tied>1&&<small>tied · {r.tied}</small>}</td><td><button aria-label={`Inspect ranking profile for ${r.name}`} aria-pressed={selected===r.key} onClick={()=>inspect(r.key)}>{r.name}</button><small>{r.district}</small></td><td><strong>{n(r.rate)}%</strong><span className="rk-bar" aria-hidden="true"><i style={{width:`${r.rate}%`}}/></span></td><td>{n(r.top!)} / {n(r.bottom!)}</td></tr>)}</tbody></table>{!visible.length&&<p className="rk-empty">{data.rows.length?'No names match this search.':'No eligible rates in this population. Inspect the exclusions below.'}</p>}</div></div>
    <aside id="subject-ranking-selected" className="rk-selected" aria-label="Selected subject ranking" aria-live="polite">{chosen?<><span className="rk-kicker">Selected source ULB</span><h3>{chosen.name}</h3><p>{chosen.district} · {definition.period}</p>{position?<><strong className="rk-rank">{position.tied>1?'Joint ':''}{position.rank}<span> / {data.rows.length}</span></strong><b>{n(position.rate)}% · {definition.label}</b><p>{data.rows.filter(r=>rankPrecision(r.rate)>rankPrecision(position.rate)).length} higher · {position.tied-1} other ULBs at the same rate · {data.rows.filter(r=>rankPrecision(r.rate)<rankPrecision(position.rate)).length} lower</p><dl><div><dt>{definition.topLabel}</dt><dd>{n(position.top!)}</dd></div><div><dt>{definition.bottomLabel}</dt><dd>{n(position.bottom!)}</dd></div></dl></>:<><strong className="rk-no-rate">Not ranked</strong><p>{held?.reasons.join('. ')}</p></>}<p>{chosen.identity?'Native source code links collection and segregation.':'Source-name candidate; cross-programme identity is not certified.'}</p>{link&&<a href={link}>Inspect programme evidence ↗</a>}<p className="rk-small">Different workloads can have the same completion rate. A high position is relative to the eligible cohort; it does not establish adequate service or target compliance.</p></>:<><span className="rk-kicker">Inspect a place</span><h3>The rank is the starting point.</h3><p>Select a ULB to see the exact numerator, denominator, tied peers and evidence available across subjects.</p></>}</aside></div>
    <section className="rk-profile" aria-label="ULB subject evidence profile"><header><div><span className="rk-kicker">Strengths, gaps & evidence coverage</span><h3>{chosen?`${chosen.name} · subject profile`:'Select a ULB to open its subject profile'}</h3></div>{chosen&&<span>{profile.filter(p=>p.ranked).length} / 5 measures linked and rankable</span>}</header>{chosen&&<><p>{reading}</p><div className="rk-profile-grid">{profile.map(p=><article key={p.definition.id}><span className="rk-kicker">{p.definition.label}</span>{p.ranked?<><strong>{n(p.ranked.rate)}%</strong><b>{p.ranked.tied>1?'Joint rank':'Rank'} {p.ranked.rank} / {p.population}</b><p>{n(p.ranked.top!)} / {n(p.ranked.bottom!)} · {p.definition.period}</p><small>All returned districts · {p.definition.id===subject?'Selected source':'Linked by native source ULB code'}</small></>:p.excluded?<><b>Not rankable</b><p>{p.excluded.reasons.join('. ')}</p></>:p.candidate?<><b>Identity not linked</b><p>A matching source name and district is available. Confirm identity before attributing its figures to this ULB.</p></>:<><b>No linked evidence</b><p>No confirmed record for this subject is attached to this source ULB. This is not a zero score.</p></>}{(p.matched||p.candidate)&&p.definition.id!==subject&&<button onClick={()=>changeSubject(p.definition.id,(p.matched??p.candidate)!.key)}>{p.matched?'Open subject ranking':'Inspect name-match candidate'} ↗</button>}</article>)}</div><p className="rk-caption">Profile ranks always use all returned districts in each subject. Reporting periods and eligible populations differ. Unconfirmed name matches do not contribute to coverage, a combined score or an overall rank.</p></>}</section>
    <details className="rk-evidence"><summary>Not ranked · {data.excluded.length} in this population</summary><p>All exclusions retain their reasons. Zero numerators are valid when the denominator is positive. Collection reach can therefore rank a zero-collection ULB whose segregation ratio is undefined.</p><div className="rk-excluded">{excluded.map(r=><button key={r.key} onClick={()=>inspect(r.key,true)}><b>{r.name} · {r.district}</b><span>{r.reasons.join(' · ')}</span></button>)}</div>{!excluded.length&&<p>No exclusions match the current search.</p>}</details>
    <details className="rk-evidence"><summary>Source, eligibility & overall-index readiness</summary><p><b>{definition.source}</b> · {definition.period}. {definition.boundary}</p><p>Identical required measurements for one source identity count once. Conflicting variants, missing or invalid measures, zero denominators and impossible rates are held out. Legacy-waste balances must also reconcile. The comparison population is the eligible retained cohort, not a claim of complete statewide coverage. {all.rows.length} candidates are eligible across all returned districts for this subject.</p><p><b>Overall index: gated by measured evidence.</b> The audit above tests the aligned July delivery sources and reports the exact overlap, valid intersection and zero-pattern concentration. Historical awards, configured capacity and unmatched name candidates do not substitute for current outcomes.</p></details>
  </section>;
}
