'use client';
import {useState,useSyncExternalStore} from 'react';
import {serviceSnapshot as data,serviceCategories,serviceCategory,serviceCoordinates,serviceExclusions,serviceRates,type ServiceCategory,type ServiceUlb} from '@/lib/ulb-service';
import './ulb-service-radar.css';
import {RadarNames} from './radar-names';
import serviceSeries from '@/data/aggregates/ulb-service-series.json';

const n=(v:number)=>v.toLocaleString('en-IN',{maximumFractionDigits:1});
const pct=(v:number|null)=>v===null?'Not defined':`${n(v)}%`;
const label=(id:ServiceCategory|null)=>serviceCategories.find(c=>c.id===id)?.label??'Outside the matrix';
/** The same matrix drawn twice: wide, and sized for a phone so the whole matrix fits without a sideways swipe. */
const frames={
  wide:{width:840,height:555,left:70,right:790,top:60,bottom:490,tickGap:13,xTickY:512,xTitleY:543,yTitleX:18,lines:1,labelClear:36,nameSize:10},
  compact:{width:400,height:452,left:52,right:388,top:22,bottom:376,tickGap:8,xTickY:394,xTitleY:428,yTitleX:11,lines:2,labelClear:46,nameSize:11.5},
};
const zoneWords:Record<ServiceCategory,[string,string]>={collection:['Investigate','collection reach'],both:['Doing well','on both'],review:['Priority review:','both measures'],segregation:['Investigate','segregation']};
const COMPACT='(max-width: 700px)';
const watchCompact=(notify:()=>void)=>{if(typeof window.matchMedia!=='function')return()=>{};const query=window.matchMedia(COMPACT);query.addEventListener('change',notify);return()=>query.removeEventListener('change',notify);};
const isCompact=()=>typeof window.matchMedia==='function'&&window.matchMedia(COMPACT).matches;

export function UlbServiceRadar(){
  const [district,setDistrict]=useState(''),[selected,setSelected]=useState(data.ulbs.find(u=>u.name==='NARSIPATNAM')?.code??''),[peer,setPeer]=useState('');
  const [category,setCategory]=useState<ServiceCategory|null>(null);
  const [collectionReference,setCollectionReference]=useState(80),[segregationReference,setSegregationReference]=useState(80);
  const compact=useSyncExternalStore(watchCompact,isCompact,()=>false),f=compact?frames.compact:frames.wide;
  const x=(v:number)=>f.left+v*(f.right-f.left)/100,y=(v:number)=>f.bottom-v*(f.bottom-f.top)/100;
  const scoped=data.ulbs.filter(u=>!district||u.district===district);
  const eligible=scoped.filter(u=>!serviceExclusions(u).length),outside=scoped.filter(u=>serviceExclusions(u).length);
  const classify=(u:ServiceUlb)=>serviceCategory(u,collectionReference,segregationReference);
  const visible=eligible.filter(u=>!category||classify(u)===category);
  const chosen=scoped.find(u=>u.code===selected),other=chosen&&!serviceExclusions(chosen).length?eligible.find(u=>u.code===peer&&u.code!==selected):undefined;
  const choose=(code:string)=>{setSelected(code);const next=scoped.find(u=>u.code===code);if(code===peer||!next||serviceExclusions(next).length)setPeer('');};
  const groups=serviceCoordinates(visible).sort((a,b)=>Number(a.ulbs.some(u=>u.code===selected))-Number(b.ulbs.some(u=>u.code===selected)));
  const zoneSize=compact?11.5:11;
  const zoneLabels=([['collection',f.left+12,'start',true],['both',f.right-12,'end',true],['review',f.left+12,'start',false],['segregation',f.right-12,'end',false]] as const).map(([id,tx,anchor,top])=>{const rows=f.lines===2?zoneWords[id]:[zoneWords[id].join(' ')];return {id,tx,anchor,rows,y:top?f.top+20:f.bottom-13-(rows.length-1)*14};});
  const zoneBoxes=zoneLabels.flatMap(z=>z.rows.map((row,i)=>{const width=row.length*zoneSize*.62;return {x:z.anchor==='end'?z.tx-width:z.tx,y:z.y+i*14,width};}));
  // The selected and compared names and the quadrant captions are already drawn; example names must steer around them.
  const reservedNames=[...zoneBoxes,...groups.flatMap(g=>{const name=g.ulbs.some(u=>u.code===selected)?chosen?.name:g.ulbs.some(u=>u.code===peer)?other?.name:undefined;if(!name)return [];const width=name.length*(compact?8:7.4),tx=x(g.collection)+(g.collection>70?-13:13);return [{x:g.collection>70?tx-width:tx,y:y(g.segregation)+(g.segregation>90?22:-13),width}];})];
  const districts=[...new Set(data.ulbs.map(u=>u.district))].sort();
  const counts=Object.fromEntries(serviceCategories.map(c=>[c.id,eligible.filter(u=>classify(u)===c.id).length]));
  const chosenRates=chosen?serviceRates(chosen):null,peerRates=other?serviceRates(other):null;
  const categoryExamples=Object.fromEntries(serviceCategories.map(c=>{const members=eligible.filter(u=>classify(u)===c.id),signal=(u:ServiceUlb)=>{const rates=serviceRates(u);return ((rates.collection??0)+(rates.segregation??0))/2;},highest=[...members].sort((a,b)=>signal(b)-signal(a)||a.name.localeCompare(b.name))[0],lowest=[...members].sort((a,b)=>signal(a)-signal(b)||a.name.localeCompare(b.name))[0];return [c.id,{highest,lowest,signal}]})) as Record<ServiceCategory,{highest:ServiceUlb|undefined;lowest:ServiceUlb|undefined;signal:(u:ServiceUlb)=>number}>;
  const xCut=x(collectionReference),yCut=y(segregationReference);
  return <section className="service-radar" aria-label="ULB service performance snapshot">
    <header className="usr-intro"><div><h2>Compare ULBs</h2><p>Collection reach × segregation · subject-specific categories</p></div><div className="usr-date"><strong>12 August 2026</strong><span>Reference day · not a latest-period rating</span></div></header>
    <div className="usr-summary"><span><strong>{eligible.length}</strong> ULBs placed</span><span><strong>{outside.length}</strong> outside the matrix</span><span>Draft references <b>{collectionReference}% collection / {segregationReference}% segregation</b></span></div>
    <details className="radar-methods"><summary>Exact formulas and how categories are assigned</summary><div className="usr-basis" role="note" aria-label="Basis of this comparison"><div><b>Horizontal · collection reach</b><span>Collected households ÷ total households × 100</span></div><div><b>Vertical · segregation</b><span>Segregating households ÷ collected households × 100</span></div><div><b>How categories are assigned</b><span>Compare each rate with its draft reference. No combined score or rank; other subjects are not included.</span></div></div></details>
    <a className="usr-rank-link" href={`/gap-radar?mode=governed&view=rankings&subject=reach${selected?`&entity=urban:${encodeURIComponent(selected)}`:''}`}>Explore subject rankings & ULB profiles ↗</a>
    <div className="usr-controls"><label>District<select aria-label="Service snapshot district" value={district} onChange={e=>{setDistrict(e.target.value);setSelected('');setPeer('');setCategory(null);}}><option value="">All returned districts</option>{districts.map(d=><option key={d}>{d}</option>)}</select></label><label>Find a ULB<select aria-label="Find service ULB" value={selected} onChange={e=>{choose(e.target.value);setCategory(null);}}><option value="">Choose a ULB</option>{scoped.map(u=><option key={u.code} value={u.code}>{u.name}{serviceExclusions(u).length?' · outside matrix':''}</option>)}</select></label><label>Compare with<select aria-label="Compare service peer" value={peer} disabled={!chosen||!!serviceExclusions(chosen).length} onChange={e=>{setPeer(e.target.value);setCategory(null);}}><option value="">Choose a peer</option>{eligible.filter(u=>u.code!==selected).map(u=><option key={u.code} value={u.code}>{u.name}</option>)}</select></label></div>
    <div className="usr-howto" role="note" aria-label="How to read this chart"><strong>How to read this chart</strong><p>Each dot is one ULB on 12 August.</p><dl><div><dt>Further right</dt><dd>More of its households had waste collected.</dd></div><div><dt>Higher up</dt><dd>More of those households segregated their waste.</dd></div><div><dt>Dashed lines</dt><dd>Draft guides at {collectionReference}% collection and {segregationReference}% segregation, not official targets.</dd></div><div><dt>“Both”</dt><dd>Collection and segregation. Top right meets both guides, bottom left is below both.</dd></div></dl></div>
    <div className="usr-stage"><div className="usr-plot">{category&&<div className="usr-plot-heading"><span>Showing one category</span><button onClick={()=>setCategory(null)}>Show all {eligible.length} ULBs ×</button></div>}<div className="usr-scroll" tabIndex={0} role="region" aria-label="Scrollable service matrix"><svg viewBox={`0 0 ${f.width} ${f.height}`} className={compact?'is-compact':undefined} role="group" aria-label="Collection coverage versus segregation among collected households">
      <rect x={f.left} y={f.top} width={xCut-f.left} height={yCut-f.top} className="usr-zone usr-collection"/><rect x={xCut} y={f.top} width={f.right-xCut} height={yCut-f.top} className="usr-zone usr-both"/>
      <rect x={f.left} y={yCut} width={xCut-f.left} height={f.bottom-yCut} className="usr-zone usr-review"/><rect x={xCut} y={yCut} width={f.right-xCut} height={f.bottom-yCut} className="usr-zone usr-segregation"/>
      {[0,20,40,60,80,100].map(t=><g key={t}><line x1={f.left} x2={f.right} y1={y(t)} y2={y(t)} className="usr-grid"/><line x1={x(t)} x2={x(t)} y1={f.top} y2={f.bottom} className="usr-grid"/><text x={f.left-f.tickGap} y={y(t)+4} textAnchor="end" className="usr-tick">{t}%</text><text x={x(t)} y={f.xTickY} textAnchor="middle" className="usr-tick">{t}%</text></g>)}
      <line x1={xCut} x2={xCut} y1={f.top} y2={f.bottom} className="usr-reference"/><line x1={f.left} x2={f.right} y1={yCut} y2={yCut} className="usr-reference"/>
      <text x={(f.left+f.right)/2} y={f.xTitleY} textAnchor="middle" className="usr-axis">Collection reach · % of households collected from</text><text transform={`translate(${f.yTitleX} ${(f.top+f.bottom)/2}) rotate(-90)`} textAnchor="middle" className="usr-axis">Segregation · % of collected households segregating</text>
      {groups.map(g=>{const active=g.ulbs.some(u=>u.code===selected),compared=g.ulbs.some(u=>u.code===peer),id=classify(g.ulbs[0]);return <g key={`${g.collection}|${g.segregation}`} role="button" tabIndex={0} aria-pressed={active} aria-label={`${g.ulbs.map(u=>u.name).join(', ')}: ${pct(g.collection)} collection, ${pct(g.segregation)} segregation; ${label(id)}`} className={`usr-dot usr-${id} ${active?'usr-selected':''} ${compared?'usr-compared':''}`} onClick={()=>choose(g.ulbs[0].code)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(g.ulbs[0].code);}}}>
        <circle cx={x(g.collection)} cy={y(g.segregation)} r="13" fill="transparent"/>{(active||compared)&&<circle cx={x(g.collection)} cy={y(g.segregation)} r="13" className="usr-halo"/>}<circle cx={x(g.collection)} cy={y(g.segregation)} r={active||compared?7:g.ulbs.length>1?7:4.5} className="usr-mark"/>{g.ulbs.length>1&&<text x={x(g.collection)} y={y(g.segregation)+3} textAnchor="middle" className="usr-count">{g.ulbs.length}</text>}{(active||compared)&&<text x={x(g.collection)+(g.collection>70?-13:13)} y={y(g.segregation)+(g.segregation>90?22:-13)} textAnchor={g.collection>70?'end':'start'} className="usr-name">{active?chosen?.name:other?.name}</text>}<title>{`${g.ulbs.map(u=>u.name).join(', ')} · ${pct(g.collection)} collection · ${pct(g.segregation)} segregation`}</title></g>;})}
      <RadarNames bounds={{left:f.left+8,right:f.right-10,top:f.top+f.labelClear,bottom:f.bottom-35}} size={f.nameSize} reserved={reservedNames} points={[...new Map(serviceCategories.flatMap(c=>[categoryExamples[c.id].highest,categoryExamples[c.id].lowest]).filter(u=>u&&u.code!==selected&&u.code!==peer&&visible.some(v=>v.code===u.code)).map(u=>{const r=serviceRates(u!);return [u!.code,{key:u!.code,name:u!.name,x:x(r.collection!),y:y(r.segregation!)}] as const;})).values()]}/>
      <g className="usr-zone-labels">{zoneLabels.map(z=><text key={z.id} x={z.tx} y={z.y} textAnchor={z.anchor}>{z.rows.map((row,i)=><tspan key={row} x={z.tx} dy={i?14:0}>{row}</tspan>)}</text>)}</g>
    </svg></div><p className="usr-footnote">A number on a dot means several ULBs sit at exactly the same position, and the ULB selector lists every one. The dashed lines stay where they are when you filter by district.</p></div>
    <aside className="usr-categories" aria-label="Performance categories"><span className="usr-kicker">Collection & segregation categories</span>{serviceCategories.map(c=>{const example=categoryExamples[c.id],high=example.highest?serviceRates(example.highest):null,low=example.lowest?serviceRates(example.lowest):null;return <button key={c.id} className={`usr-category usr-${c.id}`} aria-pressed={category===c.id} onClick={()=>{setCategory(category===c.id?null:c.id);setSelected('');setPeer('');}}><span className="usr-category-top"><b>{c.label}</b><strong>{counts[c.id]}</strong></span><span>Collection {['both','segregation'].includes(c.id)?'≥':'<'} {collectionReference}% · segregation {['both','collection'].includes(c.id)?'≥':'<'} {segregationReference}%.</span>{example.highest?<div className="usr-examples"><span>{c.id==='both'?'Potential learning peer':'Higher reported pair'} <b>{example.highest.name}</b><em>{n(high!.collection!)} / {n(high!.segregation!)}%</em></span>{example.lowest&&example.lowest.code!==example.highest.code&&<span>Lower pair <b>{example.lowest.name}</b><em>{n(low!.collection!)} / {n(low!.segregation!)}%</em></span>}</div>:<div className="usr-examples is-empty">None in this cohort</div>}</button>;})}<p>“Both” means collection reach and segregation. The dashed lines are draft guides, not department-approved targets. Named examples compare the mean of these two rates within each category; ties use alphabetical order. Potential learning peers need evidence review before transferring practices.</p></aside></div>
    <section className="usr-detail" aria-label="Selected service ULB" aria-live="polite">{chosen&&chosenRates?<><header><div><span className="usr-kicker">Selected ULB · source code {chosen.code}</span><h3>{chosen.name}</h3><p>{chosen.district} · {chosen.positiveHouseholdSecretariats} positive-household secretariats of {chosen.secretariats} paired · 12 Aug 2026</p></div><span className={`usr-position usr-${classify(chosen)??'outside'}`}>{label(classify(chosen))}</span></header><div className="usr-metrics"><div><span>Collection coverage</span><strong>{pct(chosenRates.collection)}</strong><small>{n(chosen.collected)} / {n(chosen.households)} households</small></div><div><span>Segregation among collected</span><strong>{pct(chosenRates.segregation)}</strong><small>{n(chosen.segregated)} / {n(chosen.collected)} collected households</small></div><div className="usr-interpretation"><span>What this position means</span><p>{serviceExclusions(chosen).length?serviceExclusions(chosen).join('. '):`${chosenRates.collection!>=collectionReference?'Meets':'Below'} the ${collectionReference}% collection reference and ${chosenRates.segregation!>=segregationReference?'meets':'below'} the ${segregationReference}% segregation reference. This is a reported daily service position.`}</p></div></div>
      {other&&peerRates&&<div className="usr-peer"><div><span className="usr-kicker">Peer comparison · same date and definitions</span><h4>{chosen.name} <span>versus</span> {other.name}</h4><p>{label(classify(other))} · {other.positiveHouseholdSecretariats} positive-household secretariats in {other.district}</p></div><div><span>Collection</span><strong>{pct(chosenRates.collection)} <em>vs</em> {pct(peerRates.collection)}</strong><small>{n(chosenRates.collection!-peerRates.collection!)} pp · selected minus peer</small></div><div><span>Segregation</span><strong>{pct(chosenRates.segregation)} <em>vs</em> {pct(peerRates.segregation)}</strong><small>{n(chosenRates.segregation!-peerRates.segregation!)} pp · selected minus peer</small></div></div>}
      <details className="usr-evidence"><summary>Inspect the paired source figures</summary><p>Native ULB code {chosen.code}. Only identical secretariat/date records are collapsed. Both exports agree on native identity and household denominators. Quantities below use the same paired records; percentages are ratios of sums.</p><div className="usr-table-scroll"><table><thead><tr><th>Secretariat code</th><th>Households</th><th>Collected</th><th>Segregated</th><th>Code check</th></tr></thead><tbody>{data.points.filter(p=>p[1]===chosen.code).map(p=><tr key={String(p[0])}><td>{p[0]}</td><td>{n(Number(p[2]))}</td><td>{n(Number(p[3]))}</td><td>{n(Number(p[4]))}</td><td>{p[5]?'Review mapping':'Consistent'}</td></tr>)}</tbody></table></div><p>No cross-programme Diagnostics identity is inferred from a similar ULB name.</p></details>
    </>:<p>Select a dot or choose a ULB to see its category, exact figures and peer comparison.</p>}</section>
    <details className="usr-evidence usr-outside"><summary>Outside the matrix · {outside.length} ULBs in this district selection</summary><p>Whole ULB groups are held out when any paired secretariat needs geographic-code review. Code differences can reflect geographic grain; they are not automatically source errors. Zero collection leaves the segregation ratio undefined.</p><div className="usr-outside-list">{outside.map(u=><button key={u.code} onClick={()=>{choose(u.code);setPeer('');setCategory(null);}}><b>{u.name}</b><span>{serviceExclusions(u).join(' · ')}</span></button>)}</div></details>
    <details className="usr-evidence usr-method"><summary>References, date choice & source coverage</summary><p><b>Draft analytical references, not approved targets.</b> The initial 80% lines are explicit review guides. Change them to inspect sensitivity; a ULB on a line meets that reference. Positions never change when a reference changes, only categories.</p><div className="usr-reference-controls"><label>Collection reference<select aria-label="Collection reference" value={collectionReference} onChange={e=>{setCollectionReference(Number(e.target.value));setCategory(null);}}>{[50,60,70,80,90].map(v=><option key={v} value={v}>{v}% · draft</option>)}</select></label><label>Segregation reference<select aria-label="Segregation reference" value={segregationReference} onChange={e=>{setSegregationReference(Number(e.target.value));setCategory(null);}}>{[50,60,70,80,90].map(v=><option key={v} value={v}>{v}% · draft</option>)}</select></label></div><p><b>Why one day?</b> The retained window carries household denominators on 16 days, but substantial collection figures on only 12 August. The other 15 days contain mostly stored zeros; these do not establish that collection stopped. We therefore compare ULBs on the supported reference day, rather than rank their service over the whole window.</p><details><summary>Inspect daily reporting evidence</summary><p>Collection percentages below describe stored reports and changing daily populations, not a service-performance trend.</p>{Object.entries(serviceSeries.series).map(([day,cells])=>{const valid=cells.filter(c=>c!==null&&c[0]>0),households=valid.reduce((s,c)=>s+c![0],0),collected=valid.reduce((s,c)=>s+c![1],0);return <p key={day}><b>{day}</b>: {valid.filter(c=>c![1]>0).length} of {valid.length} ULBs carry positive collection · {households?pct(collected/households*100):'Not defined'} recorded collection / households.</p>;})}</details><p><b>Definitions.</b> Collection = summed collected households / summed total households. Segregation = summed reported segregating households / summed collected households. The application interprets <code>garbage_segregation</code> as households, pending departmental definition confirmation; it is not waste tonnage or an independent environmental outcome.</p><p><b>Retained sources.</b> {Object.entries(data.generatedFrom).map(([key,s])=>`${key}: ${n(s.rows)} raw rows, ${s.pages} pages, retrieved ${s.generatedAt.slice(0,10)}`).join(' · ')}. Both sources are paired by secretariat code and day, then summed by native ULB code. The builder fails closed on conflicts, missing measures, unmatched records or impossible containment. {data.boundary}</p></details>
  </section>;
}
