'use client';
import type {CSSProperties} from 'react';
import type {PlanMonth} from '@/lib/delivery-plan';
import './evidence-expansion.css';
const n=(v:number|null)=>v===null?'Not reported':v.toLocaleString('en-IN',{maximumFractionDigits:3});
export function WorksTimeline({months,selected,onSelect,unit}:{months:PlanMonth[];selected:string|undefined;onSelect:(month:string)=>void;unit:string}) {
  const max=Math.max(1,...months.flatMap(m=>[m.target??0,m.achievement??0]));
  return <div className="works-series"><div className="works-series-key"><span><i/>Reported achievement</span><span><i/>Target</span><span><i/>Plan only · no achievement reported</span></div><div className="works-series-scroll"><div className="works-series-plot" style={{'--month-count':months.length} as CSSProperties}>{months.map(m=><button key={m.monthId} type="button" className={`works-period ${m.unreported?'plan-only':''}`} aria-pressed={selected===m.monthId} aria-label={`${m.label} ${m.year}: ${m.unreported?'plan only, achievement not reported':`${n(m.achievement)} achieved`}; target ${n(m.target)} ${unit}`} onClick={()=>onSelect(m.monthId)}><span className="works-bar-area"><i className="works-target" style={{'--bar-size':`${(m.target??0)/max*100}%`} as CSSProperties}/>{m.achievement!==null&&<i className="works-achievement" style={{'--bar-size':`${m.achievement/max*100}%`} as CSSProperties}/>}</span><b>{m.label.slice(0,3)}</b><small>{m.year}</small><span className="works-period-value">{m.unreported?'Plan':n(m.achievement)}<span className="works-mobile-target">Target {n(m.target)}</span></span></button>)}</div></div><p className="ew-caption">Each bar pair is one reported month, with a common scale in {unit}. Select a month to inspect its target, achievement and district coverage. No values are added across months.</p></div>;
}
